export interface Champion {
  year: number;
  driver: string;
  team: string;
  wins: number;
  age: number;
  location: string;
  points: string;
}

export const champions: Champion[] = [
  { year: 1950, driver: 'Nino Farina (IT)', team: 'Alfa Romeo', wins: 3, age: 44, location: 'GP Italien (7/7)', points: '30' },
  { year: 1951, driver: 'Juan Manuel Fangio (ARG)', team: 'Alfa Romeo', wins: 3, age: 40, location: 'GP Spanien (8/8)', points: '31 (37)' },
  { year: 1952, driver: 'Alberto Ascari (IT)', team: 'Ferrari', wins: 6, age: 34, location: 'GP Deutschland (6/8)', points: '36 (52,5)' },
  { year: 1953, driver: 'Alberto Ascari (IT)', team: 'Ferrari', wins: 5, age: 35, location: 'GP Schweiz (8/9)', points: '34,5 (46,5)' },
  { year: 1954, driver: 'Juan Manuel Fangio (ARG)', team: 'Mercedes, Maserati', wins: 6, age: 43, location: 'GP Schweiz (7/9)', points: '42 (57)' },
  { year: 1955, driver: 'Juan Manuel Fangio (ARG)', team: 'Mercedes', wins: 4, age: 44, location: 'GP England (6/7)', points: '40 (41)' },
  { year: 1956, driver: 'Juan Manuel Fangio (ARG)', team: 'Ferrari-Lancia', wins: 3, age: 45, location: 'GP Italien (8/8)', points: '30 (33)' },
  { year: 1957, driver: 'Juan Manuel Fangio (ARG)', team: 'Maserati', wins: 4, age: 46, location: 'GP Deutschland (6/8)', points: '40 (46)' },
  { year: 1958, driver: 'Mike Hawthorn (GB)', team: 'Ferrari', wins: 1, age: 29, location: 'GP Marokko (11/11)', points: '42 (49)' },
  { year: 1959, driver: 'Jack Brabham (AUS)', team: 'Cooper-Climax', wins: 2, age: 33, location: 'GP USA (9/9)', points: '31 (34)' },
  { year: 1960, driver: 'Jack Brabham (AUS)', team: 'Cooper-Climax', wins: 5, age: 34, location: 'GP Italien (9/10)', points: '43' },
  { year: 1961, driver: 'Phil Hill (USA)', team: 'Ferrari', wins: 2, age: 34, location: 'GP Italien (7/8)', points: '34 (38)' },
  { year: 1962, driver: 'Graham Hill (GB)', team: 'B.R.M.', wins: 4, age: 33, location: 'GP Südafrika (9/9)', points: '42 (52)' },
  { year: 1963, driver: 'Jim Clark (GB)', team: 'Lotus-Climax', wins: 7, age: 27, location: 'GP Italien (7/10)', points: '54 (73)' },
  { year: 1964, driver: 'John Surtees (GB)', team: 'Ferrari', wins: 2, age: 30, location: 'GP Mexiko (10/10)', points: '40' },
  { year: 1965, driver: 'Jim Clark (GB)', team: 'Lotus-Climax', wins: 6, age: 29, location: 'GP Deutschland (7/10)', points: '54' },
  { year: 1966, driver: 'Jack Brabham (AUS)', team: 'Brabham-Repco', wins: 4, age: 40, location: 'GP Italien (7/9)', points: '42 (45)' },
  { year: 1967, driver: 'Denis Hulme (NZ)', team: 'Brabham-Repco', wins: 2, age: 31, location: 'GP Mexiko (11/11)', points: '51' },
  { year: 1968, driver: 'Graham Hill (GB)', team: 'Lotus-Cosworth', wins: 3, age: 39, location: 'GP Mexiko (12/12)', points: '48' },
  { year: 1969, driver: 'Jackie Stewart (GB)', team: 'Matra-Cosworth', wins: 6, age: 30, location: 'GP Italien (8/11)', points: '63' },
  { year: 1970, driver: 'Jochen Rindt (A)', team: 'Lotus-Cosworth', wins: 5, age: 28, location: 'GP USA (12/13)', points: '45' },
  { year: 1971, driver: 'Jackie Stewart (GB)', team: 'Tyrrell-Cosworth', wins: 6, age: 32, location: 'GP Österreich (8/11)', points: '62' },
  { year: 1972, driver: 'Emerson Fittipaldi (BR)', team: 'Lotus-Cosworth', wins: 5, age: 25, location: 'GP Italien (10/12)', points: '61' },
  { year: 1973, driver: 'Jackie Stewart (GB)', team: 'Tyrrell-Cosworth', wins: 5, age: 34, location: 'GP Italien (13/15)', points: '71' },
  { year: 1974, driver: 'Emerson Fittipaldi (BR)', team: 'McLaren-Cosworth', wins: 3, age: 27, location: 'GP USA (15/15)', points: '55' },
  { year: 1975, driver: 'Niki Lauda (A)', team: 'Ferrari', wins: 5, age: 26, location: 'GP Italien (13/14)', points: '64,5' },
  { year: 1976, driver: 'James Hunt (GB)', team: 'McLaren-Cosworth', wins: 6, age: 29, location: 'GP Japan (16/16)', points: '69' },
  { year: 1977, driver: 'Niki Lauda (A)', team: 'Ferrari', wins: 3, age: 28, location: 'GP USA (15/17)', points: '72' },
  { year: 1978, driver: 'Mario Andretti (USA)', team: 'Lotus-Cosworth', wins: 6, age: 38, location: 'GP Italien (14/16)', points: '64' },
  { year: 1979, driver: 'Jody Scheckter (SA)', team: 'Ferrari', wins: 3, age: 29, location: 'GP Italien (13/15)', points: '51 (60)' },
  { year: 1980, driver: 'Alan Jones (AUS)', team: 'Williams-Cosworth', wins: 5, age: 34, location: 'GP Kanada (13/14)', points: '67 (71)' },
  { year: 1981, driver: 'Nelson Piquet (BR)', team: 'Brabham-Cosworth', wins: 3, age: 29, location: 'GP USA-Mitte (15/15)', points: '50' },
  { year: 1982, driver: 'Keke Rosberg (FIN)', team: 'Williams-Cosworth', wins: 1, age: 34, location: 'GP USA-Mitte (16/16)', points: '44' },
  { year: 1983, driver: 'Nelson Piquet (BR)', team: 'Brabham-BMW', wins: 3, age: 31, location: 'GP Südafrika (15/15)', points: '59' },
  { year: 1984, driver: 'Niki Lauda (A)', team: 'McLaren-Porsche', wins: 5, age: 35, location: 'GP Portugal (16/16)', points: '72' },
  { year: 1985, driver: 'Alain Prost (F)', team: 'McLaren-Porsche', wins: 5, age: 30, location: 'GP Europa (14/16)', points: '73 (76)' },
  { year: 1986, driver: 'Alain Prost (F)', team: 'McLaren-Porsche', wins: 4, age: 31, location: 'GP Australien (16/16)', points: '72 (74)' },
  { year: 1987, driver: 'Nelson Piquet (BR)', team: 'Williams-Honda', wins: 3, age: 35, location: 'GP Japan (15/16)', points: '73 (76)' },
  { year: 1988, driver: 'Ayrton Senna (BR)', team: 'McLaren-Honda', wins: 8, age: 28, location: 'GP Japan (15/16)', points: '90 (94)' },
  { year: 1989, driver: 'Alain Prost (F)', team: 'McLaren-Honda', wins: 4, age: 34, location: 'GP Japan (15/16)', points: '76 (81)' },
  { year: 1990, driver: 'Ayrton Senna (BR)', team: 'McLaren-Honda', wins: 6, age: 30, location: 'GP Japan (15/16)', points: '78' },
  { year: 1991, driver: 'Ayrton Senna (BR)', team: 'McLaren-Honda', wins: 7, age: 31, location: 'GP Japan (15/16)', points: '96' },
  { year: 1992, driver: 'Nigel Mansell (GB)', team: 'Williams-Renault', wins: 9, age: 39, location: 'GP Ungarn (11/16)', points: '108' },
  { year: 1993, driver: 'Alain Prost (F)', team: 'Williams-Renault', wins: 7, age: 38, location: 'GP Portugal (14/16)', points: '99' },
  { year: 1994, driver: 'Michael Schumacher (D)', team: 'Benetton-Ford', wins: 8, age: 25, location: 'GP Australien (16/16)', points: '92' },
  { year: 1995, driver: 'Michael Schumacher (D)', team: 'Benetton-Renault', wins: 9, age: 26, location: 'GP Pazifik (15/17)', points: '102' },
  { year: 1996, driver: 'Damon Hill (GB)', team: 'Williams-Renault', wins: 8, age: 36, location: 'GP Japan (16/16)', points: '97' },
  { year: 1997, driver: 'Jacques Villeneuve (CDN)', team: 'Williams-Renault', wins: 7, age: 26, location: 'GP Europa (17/17)', points: '81' },
  { year: 1998, driver: 'Mika Häkkinen (FIN)', team: 'McLaren-Mercedes', wins: 8, age: 30, location: 'GP Japan (16/16)', points: '100' },
  { year: 1999, driver: 'Mika Häkkinen (FIN)', team: 'McLaren-Mercedes', wins: 5, age: 31, location: 'GP Japan (16/16)', points: '76' },
  { year: 2000, driver: 'Michael Schumacher (D)', team: 'Ferrari', wins: 9, age: 31, location: 'GP Japan (16/17)', points: '108' },
  { year: 2001, driver: 'Michael Schumacher (D)', team: 'Ferrari', wins: 9, age: 32, location: 'GP Ungarn (13/17)', points: '123' },
  { year: 2002, driver: 'Michael Schumacher (D)', team: 'Ferrari', wins: 11, age: 33, location: 'GP Frankreich (11/17)', points: '144' },
  { year: 2003, driver: 'Michael Schumacher (D)', team: 'Ferrari', wins: 6, age: 34, location: 'GP Japan (16/16)', points: '93' },
  { year: 2004, driver: 'Michael Schumacher (D)', team: 'Ferrari', wins: 13, age: 35, location: 'GP Belgien (14/18)', points: '148' },
  { year: 2005, driver: 'Fernando Alonso (E)', team: 'Renault', wins: 7, age: 24, location: 'GP Brasilien (17/19)', points: '133' },
  { year: 2006, driver: 'Fernando Alonso (E)', team: 'Renault', wins: 7, age: 25, location: 'GP Brasilien (18/18)', points: '134' },
  { year: 2007, driver: 'Kimi Räikkönen (FIN)', team: 'Ferrari', wins: 6, age: 28, location: 'GP Brasilien (17/17)', points: '110' },
  { year: 2008, driver: 'Lewis Hamilton (GB)', team: 'McLaren-Mercedes', wins: 5, age: 23, location: 'GP Brasilien (18/18)', points: '98' },
  { year: 2009, driver: 'Jenson Button (GB)', team: 'Brawn-GP-Mercedes', wins: 6, age: 29, location: 'GP Brasilien (16/17)', points: '95' },
  { year: 2010, driver: 'Sebastian Vettel (D)', team: 'Red-Bull-Renault', wins: 5, age: 23, location: 'GP Abu Dhabi (19/19)', points: '256' },
  { year: 2011, driver: 'Sebastian Vettel (D)', team: 'Red-Bull-Renault', wins: 11, age: 24, location: 'GP Japan (15/19)', points: '392' },
  { year: 2012, driver: 'Sebastian Vettel (D)', team: 'Red-Bull-Renault', wins: 5, age: 25, location: 'GP Brasilien (20/20)', points: '281' },
  { year: 2013, driver: 'Sebastian Vettel (D)', team: 'Red-Bull-Renault', wins: 13, age: 26, location: 'GP Indien (16/19)', points: '397' },
  { year: 2014, driver: 'Lewis Hamilton (GB)', team: 'Mercedes', wins: 11, age: 29, location: 'GP Abu Dhabi (19/19)', points: '384' },
  { year: 2015, driver: 'Lewis Hamilton (GB)', team: 'Mercedes', wins: 10, age: 30, location: 'GP USA (16/19)', points: '381' },
  { year: 2016, driver: 'Nico Rosberg (D)', team: 'Mercedes', wins: 9, age: 31, location: 'GP Abu Dhabi (21/21)', points: '385' },
  { year: 2017, driver: 'Lewis Hamilton (GB)', team: 'Mercedes', wins: 9, age: 32, location: 'GP Mexiko (18/20)', points: '363' },
  { year: 2018, driver: 'Lewis Hamilton (GB)', team: 'Mercedes', wins: 11, age: 33, location: 'GP Mexiko (19/21)', points: '408' },
  { year: 2019, driver: 'Lewis Hamilton (GB)', team: 'Mercedes', wins: 11, age: 34, location: 'GP USA (19/21)', points: '413' },
  { year: 2020, driver: 'Lewis Hamilton (GB)', team: 'Mercedes', wins: 11, age: 35, location: 'GP Türkei (14/17)', points: '347' },
  { year: 2021, driver: 'Max Verstappen (NL)', team: 'Red-Bull-Honda', wins: 10, age: 24, location: 'GP Abu Dhabi (22/22)', points: '395,5' },
  { year: 2022, driver: 'Max Verstappen (NL)', team: 'Red-Bull-Honda', wins: 15, age: 25, location: 'GP Japan (18/22)', points: '454' },
  { year: 2023, driver: 'Max Verstappen (NL)', team: 'Red-Bull-Honda', wins: 19, age: 26, location: 'GP Katar (17/22)', points: '575' },
  { year: 2024, driver: 'Max Verstappen (NL)', team: 'Red-Bull-Honda', wins: 9, age: 27, location: 'GP Las Vegas (21/24)', points: '437' },
];
