export interface ConstructorChampion {
  year: number;
  constructor: string;
  engine: string;
  wins: number;
  points: string;
}

export const constructorChampions: ConstructorChampion[] = [
  { year: 1958, constructor: 'Vanwall', engine: 'Vanwall', wins: 6, points: '48 (57)' },
  { year: 1959, constructor: 'Cooper', engine: 'Climax', wins: 5, points: '40 (53)' },
  { year: 1960, constructor: 'Cooper', engine: 'Climax', wins: 6, points: '48 (58)' },
  { year: 1961, constructor: 'Ferrari', engine: 'Ferrari', wins: 5, points: '40 (52)' },
  { year: 1962, constructor: 'BRM', engine: 'BRM', wins: 4, points: '42 (56)' },
  { year: 1963, constructor: 'Lotus', engine: 'Climax', wins: 7, points: '54 (74)' },
  { year: 1964, constructor: 'Ferrari', engine: 'Ferrari', wins: 3, points: '45 (49)' },
  { year: 1965, constructor: 'Lotus', engine: 'Climax', wins: 6, points: '54 (58)' },
  { year: 1966, constructor: 'Brabham', engine: 'Repco', wins: 4, points: '42 (49)' },
  { year: 1967, constructor: 'Brabham', engine: 'Repco', wins: 4, points: '63 (67)' },
  { year: 1968, constructor: 'Lotus', engine: 'Ford', wins: 5, points: '62' },
  { year: 1969, constructor: 'Matra', engine: 'Ford', wins: 6, points: '66' },
  { year: 1970, constructor: 'Lotus', engine: 'Ford', wins: 6, points: '59' },
  { year: 1971, constructor: 'Tyrrell', engine: 'Ford', wins: 7, points: '73' },
  { year: 1972, constructor: 'Lotus', engine: 'Ford', wins: 5, points: '61' },
  { year: 1973, constructor: 'Lotus', engine: 'Ford', wins: 7, points: '92 (96)' },
  { year: 1974, constructor: 'McLaren', engine: 'Ford', wins: 4, points: '73 (75)' },
  { year: 1975, constructor: 'Ferrari', engine: 'Ferrari', wins: 6, points: '72,5' },
  { year: 1976, constructor: 'Ferrari', engine: 'Ferrari', wins: 6, points: '83' },
  { year: 1977, constructor: 'Ferrari', engine: 'Ferrari', wins: 4, points: '95 (97)' },
  { year: 1978, constructor: 'Lotus', engine: 'Ford', wins: 8, points: '86' },
  { year: 1979, constructor: 'Ferrari', engine: 'Ferrari', wins: 6, points: '113' },
  { year: 1980, constructor: 'Williams', engine: 'Ford', wins: 6, points: '120' },
  { year: 1981, constructor: 'Williams', engine: 'Ford', wins: 4, points: '95' },
  { year: 1982, constructor: 'Ferrari', engine: 'Ferrari', wins: 3, points: '74' },
  { year: 1983, constructor: 'Ferrari', engine: 'Ferrari', wins: 4, points: '89' },
  { year: 1984, constructor: 'McLaren', engine: 'TAG', wins: 12, points: '143,5' },
  { year: 1985, constructor: 'McLaren', engine: 'TAG', wins: 6, points: '90' },
  { year: 1986, constructor: 'Williams', engine: 'Honda', wins: 9, points: '141' },
  { year: 1987, constructor: 'Williams', engine: 'Honda', wins: 9, points: '137' },
  { year: 1988, constructor: 'McLaren', engine: 'Honda', wins: 15, points: '199' },
  { year: 1989, constructor: 'McLaren', engine: 'Honda', wins: 10, points: '141' },
  { year: 1990, constructor: 'McLaren', engine: 'Honda', wins: 6, points: '121' },
  { year: 1991, constructor: 'McLaren', engine: 'Honda', wins: 8, points: '139' },
  { year: 1992, constructor: 'Williams', engine: 'Renault', wins: 10, points: '164' },
  { year: 1993, constructor: 'Williams', engine: 'Renault', wins: 10, points: '168' },
  { year: 1994, constructor: 'Williams', engine: 'Renault', wins: 7, points: '118' },
  { year: 1995, constructor: 'Benetton', engine: 'Renault', wins: 11, points: '137' },
  { year: 1996, constructor: 'Williams', engine: 'Renault', wins: 12, points: '175' },
  { year: 1997, constructor: 'Williams', engine: 'Renault', wins: 8, points: '123' },
  { year: 1998, constructor: 'McLaren', engine: 'Mercedes', wins: 9, points: '156' },
  { year: 1999, constructor: 'Ferrari', engine: 'Ferrari', wins: 6, points: '128' },
  { year: 2000, constructor: 'Ferrari', engine: 'Ferrari', wins: 10, points: '170' },
  { year: 2001, constructor: 'Ferrari', engine: 'Ferrari', wins: 9, points: '179' },
  { year: 2002, constructor: 'Ferrari', engine: 'Ferrari', wins: 15, points: '221' },
  { year: 2003, constructor: 'Ferrari', engine: 'Ferrari', wins: 8, points: '158' },
  { year: 2004, constructor: 'Ferrari', engine: 'Ferrari', wins: 15, points: '262' },
  { year: 2005, constructor: 'Renault', engine: 'Renault', wins: 8, points: '191' },
  { year: 2006, constructor: 'Renault', engine: 'Renault', wins: 8, points: '206' },
  { year: 2007, constructor: 'Ferrari', engine: 'Ferrari', wins: 9, points: '204' },
  { year: 2008, constructor: 'Ferrari', engine: 'Ferrari', wins: 8, points: '172' },
  { year: 2009, constructor: 'Brawn', engine: 'Mercedes', wins: 8, points: '172' },
  { year: 2010, constructor: 'Red Bull', engine: 'Renault', wins: 9, points: '498' },
  { year: 2011, constructor: 'Red Bull', engine: 'Renault', wins: 12, points: '650' },
  { year: 2012, constructor: 'Red Bull', engine: 'Renault', wins: 7, points: '460' },
  { year: 2013, constructor: 'Red Bull', engine: 'Renault', wins: 13, points: '596' },
  { year: 2014, constructor: 'Mercedes', engine: 'Mercedes', wins: 16, points: '701' },
  { year: 2015, constructor: 'Mercedes', engine: 'Mercedes', wins: 16, points: '703' },
  { year: 2016, constructor: 'Mercedes', engine: 'Mercedes', wins: 19, points: '765' },
  { year: 2017, constructor: 'Mercedes', engine: 'Mercedes', wins: 12, points: '668' },
  { year: 2018, constructor: 'Mercedes', engine: 'Mercedes', wins: 11, points: '655' },
  { year: 2019, constructor: 'Mercedes', engine: 'Mercedes', wins: 15, points: '739' },
  { year: 2020, constructor: 'Mercedes', engine: 'Mercedes', wins: 13, points: '573' },
  { year: 2021, constructor: 'Mercedes', engine: 'Mercedes', wins: 9, points: '613,5' },
  { year: 2022, constructor: 'Red Bull', engine: 'RBPT', wins: 17, points: '759' },
  { year: 2023, constructor: 'Red Bull', engine: 'Honda RBPT', wins: 21, points: '860' },
  { year: 2024, constructor: 'McLaren', engine: 'Mercedes', wins: 8, points: '666' }
];
