export interface Team {
  id: string;
  name: string;
  fullName: string;
  base: string;
  founded: number;
  f1Start: number;
  f1End: number | 'aktiv';
  championships: number;
  wins: number;
  teamPrincipal: string;
  drivers: string[];
  description: string;
  imageUrl: string;
  color: string;
}

export const teams: Team[] = [
  {
    id: 'ferrari',
    name: 'Ferrari',
    fullName: 'Scuderia Ferrari',
    base: 'Maranello, Italien',
    founded: 1929,
    f1Start: 1950,
    f1End: 'aktiv',
    championships: 16,
    wins: 243,
    teamPrincipal: 'Frédéric Vasseur',
    drivers: ['Michael Schumacher', 'Niki Lauda', 'Alberto Ascari', 'Juan Manuel Fangio', 'Kimi Räikkönen', 'Fernando Alonso', 'Sebastian Vettel', 'Charles Leclerc', 'Carlos Sainz'],
    description: 'Das älteste und erfolgreichste Team in der Geschichte der Formel 1. Ferrari ist das einzige Team, das seit der ersten Saison 1950 ununterbrochen an der Weltmeisterschaft teilnimmt.',
    imageUrl: 'https://logo.clearbit.com/ferrari.com',
    color: '#dc2626' // red-600
  },
  {
    id: 'mclaren',
    name: 'McLaren',
    fullName: 'McLaren Formula 1 Team',
    base: 'Woking, Großbritannien',
    founded: 1963,
    f1Start: 1966,
    f1End: 'aktiv',
    championships: 8,
    wins: 183,
    teamPrincipal: 'Andrea Stella',
    drivers: ['Ayrton Senna', 'Alain Prost', 'Mika Häkkinen', 'Lewis Hamilton', 'Niki Lauda', 'James Hunt', 'Lando Norris', 'Oscar Piastri'],
    description: 'Gegründet von Bruce McLaren, ist es das zweitälteste aktive Team. McLaren erlebte seine dominanteste Phase in den späten 80er und frühen 90er Jahren mit Senna und Prost.',
    imageUrl: 'https://logo.clearbit.com/mclaren.com',
    color: '#f97316' // orange-500
  },
  {
    id: 'mercedes',
    name: 'Mercedes',
    fullName: 'Mercedes-AMG Petronas F1 Team',
    base: 'Brackley, Großbritannien',
    founded: 1954,
    f1Start: 1954,
    f1End: 'aktiv',
    championships: 8,
    wins: 125,
    teamPrincipal: 'Toto Wolff',
    drivers: ['Lewis Hamilton', 'Nico Rosberg', 'Valtteri Bottas', 'George Russell', 'Michael Schumacher', 'Juan Manuel Fangio'],
    description: 'Nach frühen Erfolgen in den 1950er Jahren kehrte Mercedes 2010 als Werksteam zurück und dominierte die Turbo-Hybrid-Ära ab 2014 mit acht Konstrukteurstiteln in Folge.',
    imageUrl: 'https://logo.clearbit.com/mercedesamgf1.com',
    color: '#0ea5e9' // sky-500
  },
  {
    id: 'red_bull',
    name: 'Red Bull',
    fullName: 'Oracle Red Bull Racing',
    base: 'Milton Keynes, Großbritannien',
    founded: 2005,
    f1Start: 2005,
    f1End: 'aktiv',
    championships: 6,
    wins: 113,
    teamPrincipal: 'Christian Horner',
    drivers: ['Sebastian Vettel', 'Max Verstappen', 'Mark Webber', 'Daniel Ricciardo', 'Sergio Pérez'],
    description: 'Hervorgegangen aus dem Jaguar-Team, stieg Red Bull schnell zu einem Top-Team auf. Sie dominierten mit Sebastian Vettel (2010-2013) und später mit Max Verstappen.',
    imageUrl: 'https://logo.clearbit.com/redbullracing.com',
    color: '#1d4ed8' // blue-700
  },
  {
    id: 'williams',
    name: 'Williams',
    fullName: 'Williams Racing',
    base: 'Grove, Großbritannien',
    founded: 1977,
    f1Start: 1977,
    f1End: 'aktiv',
    championships: 9,
    wins: 114,
    teamPrincipal: 'James Vowles',
    drivers: ['Nigel Mansell', 'Alain Prost', 'Damon Hill', 'Jacques Villeneuve', 'Nelson Piquet', 'Keke Rosberg', 'Alexander Albon'],
    description: 'Eines der erfolgreichsten Privatteams der Geschichte, gegründet von Frank Williams und Patrick Head. Dominierte weite Teile der 80er und 90er Jahre.',
    imageUrl: 'https://logo.clearbit.com/williamsf1.com',
    color: '#3b82f6' // blue-500
  },
  {
    id: 'lotus',
    name: 'Lotus',
    fullName: 'Team Lotus',
    base: 'Hethel, Großbritannien',
    founded: 1952,
    f1Start: 1958,
    f1End: 1994,
    championships: 7,
    wins: 79,
    teamPrincipal: 'Colin Chapman',
    drivers: ['Jim Clark', 'Graham Hill', 'Jochen Rindt', 'Emerson Fittipaldi', 'Mario Andretti', 'Ayrton Senna'],
    description: 'Unter der Leitung des genialen Konstrukteurs Colin Chapman revolutionierte Lotus die Formel 1 mehrfach durch Innovationen wie das Monocoque-Chassis und Ground Effect.',
    imageUrl: 'https://logo.clearbit.com/lotuscars.com',
    color: '#eab308' // yellow-500
  },
  {
    id: 'renault',
    name: 'Renault',
    fullName: 'Renault F1 Team',
    base: 'Enstone, Großbritannien / Viry-Châtillon, Frankreich',
    founded: 1977,
    f1Start: 1977,
    f1End: 2020,
    championships: 2,
    wins: 35,
    teamPrincipal: 'Flavio Briatore / Cyril Abiteboul',
    drivers: ['Fernando Alonso', 'Alain Prost', 'René Arnoux', 'Giancarlo Fisichella', 'Daniel Ricciardo'],
    description: 'Pioniere des Turbomotors in der Formel 1. Das Team gewann 2005 und 2006 mit Fernando Alonso die Weltmeisterschaft. Tritt heute als Alpine an.',
    imageUrl: 'https://logo.clearbit.com/renault.com',
    color: '#fde047' // yellow-300
  },
  {
    id: 'brabham',
    name: 'Brabham',
    fullName: 'Motor Racing Developments',
    base: 'Milton Keynes, Großbritannien',
    founded: 1960,
    f1Start: 1962,
    f1End: 1992,
    championships: 2,
    wins: 35,
    teamPrincipal: 'Jack Brabham / Bernie Ecclestone',
    drivers: ['Jack Brabham', 'Denny Hulme', 'Nelson Piquet', 'Niki Lauda', 'Riccardo Patrese'],
    description: 'Gegründet vom dreifachen Weltmeister Jack Brabham, der 1966 als einziger Fahrer in einem selbst konstruierten Auto Weltmeister wurde. Später von Bernie Ecclestone übernommen.',
    imageUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Brabham&backgroundColor=1e3a8a&textColor=ffffff',
    color: '#1e3a8a' // blue-900
  },
  {
    id: 'benetton',
    name: 'Benetton',
    fullName: 'Benetton Formula',
    base: 'Enstone, Großbritannien',
    founded: 1986,
    f1Start: 1986,
    f1End: 2001,
    championships: 1,
    wins: 27,
    teamPrincipal: 'Flavio Briatore',
    drivers: ['Michael Schumacher', 'Nelson Piquet', 'Gerhard Berger', 'Jean Alesi', 'Giancarlo Fisichella'],
    description: 'Bekannt für bunte Farben und den Aufstieg von Michael Schumacher, der mit dem Team 1994 und 1995 seine ersten beiden Weltmeistertitel gewann. Wurde später vom Renault-Konzern übernommen.',
    imageUrl: 'https://logo.clearbit.com/benetton.com',
    color: '#22c55e' // green-500
  },
  {
    id: 'tyrrell',
    name: 'Tyrrell',
    fullName: 'Tyrrell Racing Organisation',
    base: 'Ockham, Großbritannien',
    founded: 1958,
    f1Start: 1970,
    f1End: 1998,
    championships: 1,
    wins: 23,
    teamPrincipal: 'Ken Tyrrell',
    drivers: ['Jackie Stewart', 'François Cevert', 'Jody Scheckter', 'Ronnie Peterson', 'Michele Alboreto'],
    description: 'Erreichte große Erfolge in den frühen 1970er Jahren mit Jackie Stewart. Berühmt auch für den P34, das einzige sechsrädrige Auto, das je ein F1-Rennen gewann.',
    imageUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Tyrrell&backgroundColor=1e40af&textColor=ffffff',
    color: '#1e40af' // blue-800
  },
  {
    id: 'aston_martin',
    name: 'Aston Martin',
    fullName: 'Aston Martin Aramco F1 Team',
    base: 'Silverstone, Großbritannien',
    founded: 2021,
    f1Start: 1959,
    f1End: 'aktiv',
    championships: 0,
    wins: 0,
    teamPrincipal: 'Mike Krack',
    drivers: ['Fernando Alonso', 'Lance Stroll', 'Sebastian Vettel'],
    description: 'Nach einem kurzen Engagement in den späten 1950er Jahren kehrte die britische Kultmarke 2021 durch die Übernahme von Racing Point (ehemals Force India) in die Formel 1 zurück.',
    imageUrl: 'https://logo.clearbit.com/astonmartinf1.com',
    color: '#047857' // emerald-700
  },
  {
    id: 'alpine',
    name: 'Alpine',
    fullName: 'BWT Alpine F1 Team',
    base: 'Enstone, Großbritannien / Viry-Châtillon, Frankreich',
    founded: 2021,
    f1Start: 2021,
    f1End: 'aktiv',
    championships: 0,
    wins: 1,
    teamPrincipal: 'Bruno Famin',
    drivers: ['Esteban Ocon', 'Pierre Gasly', 'Fernando Alonso'],
    description: 'Das Nachfolgeteam von Renault, umbenannt zur Bewerbung der Sportwagenmarke Alpine. Feierte 2021 in Ungarn mit Esteban Ocon den ersten Sieg.',
    imageUrl: 'https://logo.clearbit.com/alpinecars.com',
    color: '#db2777' // pink-600
  },
  {
    id: 'sauber',
    name: 'Sauber',
    fullName: 'Stake F1 Team Kick Sauber',
    base: 'Hinwil, Schweiz',
    founded: 1993,
    f1Start: 1993,
    f1End: 'aktiv',
    championships: 0,
    wins: 1,
    teamPrincipal: 'Alessandro Alunni Bravi',
    drivers: ['Kimi Räikkönen', 'Felipe Massa', 'Robert Kubica', 'Charles Leclerc', 'Valtteri Bottas', 'Zhou Guanyu'],
    description: 'Das Schweizer Traditionsteam von Peter Sauber. Trat zwischenzeitlich als BMW Sauber und Alfa Romeo an. Bekannt als Talentschmiede für zukünftige Weltmeister.',
    imageUrl: 'https://logo.clearbit.com/sauber-group.com',
    color: '#22c55e' // green-500
  },
  {
    id: 'haas',
    name: 'Haas',
    fullName: 'MoneyGram Haas F1 Team',
    base: 'Kannapolis, USA',
    founded: 2016,
    f1Start: 2016,
    f1End: 'aktiv',
    championships: 0,
    wins: 0,
    teamPrincipal: 'Ayao Komatsu',
    drivers: ['Romain Grosjean', 'Kevin Magnussen', 'Mick Schumacher', 'Nico Hülkenberg'],
    description: 'Das erste amerikanische Formel-1-Team seit Jahrzehnten, gegründet von Gene Haas. Bekannt für die enge technische Partnerschaft mit Ferrari.',
    imageUrl: 'https://logo.clearbit.com/haasf1team.com',
    color: '#ef4444' // red-500
  },
  {
    id: 'jordan',
    name: 'Jordan',
    fullName: 'Jordan Grand Prix',
    base: 'Silverstone, Großbritannien',
    founded: 1991,
    f1Start: 1991,
    f1End: 2005,
    championships: 0,
    wins: 4,
    teamPrincipal: 'Eddie Jordan',
    drivers: ['Michael Schumacher', 'Rubens Barrichello', 'Ralf Schumacher', 'Damon Hill', 'Heinz-Harald Frentzen'],
    description: 'Das Team des charismatischen Iren Eddie Jordan. Michael Schumacher gab hier sein legendäres Debüt. Gewann 1998 in Spa sensationell einen Doppelsieg.',
    imageUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Jordan&backgroundColor=fbbf24&textColor=000000',
    color: '#fbbf24' // amber-400
  },
  {
    id: 'honda',
    name: 'Honda',
    fullName: 'Honda Racing F1 Team',
    base: 'Brackley, Großbritannien',
    founded: 1964,
    f1Start: 1964,
    f1End: 2008,
    championships: 0,
    wins: 3,
    teamPrincipal: 'Ross Brawn',
    drivers: ['John Surtees', 'Richie Ginther', 'Jenson Button', 'Rubens Barrichello'],
    description: 'Honda war in den 60ern und später in den 2000ern als Werksteam aktiv. Das Team wurde Ende 2008 an Ross Brawn verkauft und gewann als Brawn GP 2009 den Titel.',
    imageUrl: 'https://logo.clearbit.com/honda.com',
    color: '#dc2626' // red-600
  },
  {
    id: 'brawn',
    name: 'Brawn GP',
    fullName: 'Brawn GP Formula One Team',
    base: 'Brackley, Großbritannien',
    founded: 2009,
    f1Start: 2009,
    f1End: 2009,
    championships: 1,
    wins: 8,
    teamPrincipal: 'Ross Brawn',
    drivers: ['Jenson Button', 'Rubens Barrichello'],
    description: 'Das Märchen der Formel 1: Entstanden aus den Überresten des Honda-Teams, dominierte Brawn GP mit dem innovativen Doppeldiffusor die Saison 2009 und wurde danach zu Mercedes.',
    imageUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Brawn&backgroundColor=84cc16&textColor=ffffff',
    color: '#84cc16' // lime-500
  }
];
